In [15]:
import pandas as pd
from feature_selection.SelectKRegression import selectKRegressionResult
from feature_selection import RFE_Regression
from feature_reduction import lda_regression
from feature_reduction import pca_regression

In [16]:
BASE_PATH = "../data_collection/"
dataset1 = pd.read_csv(BASE_PATH + "prep_amazon_delivery_1.csv")

selectKResult = selectKRegressionResult(dataset1, "Delivery_Duration", k=10)
print(selectKResult)

Selected Features: ['Agent_Age', 'Agent_Rating', 'Traffic', 'Weather_Sunny', 'Category_Grocery', 'Area_Urban', 'hour', 'is_peak', 'peak_x_traffic', 'hour_sin']
                 RFR       GBR    Linear      SVMl     SVMnl  Decision  \
Regression  0.652029  0.654975  0.547451  0.541566  0.601372  0.577549

              Random
Regression  0.609212

In [17]:
rfeResult = RFE_Regression.rfe_regression_result(dataset1, 'Delivery_Duration')
rfeResult

Selected Features: ['Agent_Rating', 'Weather_Sandstorms', 'Weather_Stormy', 'Weather_Sunny', 'Weather_Windy', 'Vehicle_van', 'Category_Grocery', 'Area_Other', 'Area_Semi-Urban', 'Area_Urban']

       Linear       SVM  Decision    Random
RFE  0.413501  0.424849  0.473443  0.474052

In [18]:
ldaResult = lda_regression.lda_regression_result(dataset1, 'Delivery_Duration')
ldaResult

               Model          MSE       RMSE  R2 Score
0  Linear Regression  1129.391481  33.606420  0.587357
1                SVM  1047.060340  32.358312  0.617438
2                KNN  1222.272350  34.961012  0.553422
3      Decision Tree  2015.002841  44.888783  0.263784
4      Random Forest  1168.888034  34.189005  0.572927

               Model          MSE       RMSE  R2 Score
0  Linear Regression  1129.391481  33.606420  0.587357
1                SVM  1047.060340  32.358312  0.617438
2                KNN  1222.272350  34.961012  0.553422
3      Decision Tree  2015.002841  44.888783  0.263784
4      Random Forest  1168.888034  34.189005  0.572927

In [19]:
pcaResult = pca_regression.pca_regression_result(dataset1, 'Delivery_Duration')
pcaResult

Explained Variance Ratio: [0.09937978 0.0812973  0.03971704 0.03379398 0.03294668]
Total Variance Covered: 0.2871347824317132
               Model          MSE       RMSE  R2 Score
0  Linear Regression  2129.564634  46.147206  0.221927
1                SVM  2022.687989  44.974304  0.260976
2                KNN  1821.224798  42.675810  0.334584
3      Decision Tree  2629.872434  51.282282  0.039131
4      Random Forest  1367.887084  36.984958  0.500219

               Model          MSE       RMSE  R2 Score
0  Linear Regression  2129.564634  46.147206  0.221927
1                SVM  2022.687989  44.974304  0.260976
2                KNN  1821.224798  42.675810  0.334584
3      Decision Tree  2629.872434  51.282282  0.039131
4      Random Forest  1367.887084  36.984958  0.500219