In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("Placement.csv")

In [2]:
from Univariate import Univariate
obj = Univariate()

quan, qual = obj.quanQual(dataset)

In [3]:
print(quan)
print(qual)
dataset['ssc_p'].mean()

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']
['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

np.float64(67.30339534883721)

In [4]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [5]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%", "IQR", "1.5rule", "Lesser", "Greater", "Min", "Max", "LowOutLier", "HighOutLier"], columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName]=dataset[columnName].mean()
    descriptive.loc["Median", columnName]=dataset[columnName].median()
    descriptive.loc["Mode", columnName]=dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName]=dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName]=dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName]=dataset[columnName].quantile(0.75)
    descriptive.loc["Q4:100%", columnName]=dataset[columnName].quantile(1)
    descriptive.loc["IQR", columnName]=dataset[columnName].quantile(0.75)-dataset[columnName].quantile(0.25)
    descriptive.loc["1.5rule", columnName]=1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Lesser", columnName]=dataset[columnName].quantile(0.25)-descriptive.loc["1.5rule", columnName]
    descriptive.loc["Greater", columnName]=dataset[columnName].quantile(0.75)+descriptive.loc["1.5rule", columnName]
    descriptive.loc["Min", columnName]=dataset[columnName].min()
    descriptive.loc["Max", columnName]=dataset[columnName].max()
    descriptive.loc["LowOutLier", columnName]=dataset[columnName].min()<descriptive.loc["Lesser", columnName]
    descriptive.loc["HighOutLier", columnName]=dataset[columnName].max()>descriptive.loc["Greater", columnName]

descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0
LowOutLier,False,False,True,False,False,False,False
HighOutLier,False,False,True,True,False,False,True

In [6]:
for columnName in quan:
    
    lesser=descriptive.loc["Lesser",columnName]
    greater=descriptive.loc["Greater",columnName]
    
    dataset[columnName]=dataset[columnName].clip(lower=lesser, upper=greater)

In [8]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%", "IQR", "1.5rule", "Lesser", "Greater", "Min", "Max", "LowOutLier", "HighOutLier"], columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName]=dataset[columnName].mean()
    descriptive.loc["Median", columnName]=dataset[columnName].median()
    descriptive.loc["Mode", columnName]=dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName]=dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName]=dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName]=dataset[columnName].quantile(0.75)
    descriptive.loc["Q4:100%", columnName]=dataset[columnName].quantile(1)
    descriptive.loc["IQR", columnName]=dataset[columnName].quantile(0.75)-dataset[columnName].quantile(0.25)
    descriptive.loc["1.5rule", columnName]=1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Lesser", columnName]=dataset[columnName].quantile(0.25)-descriptive.loc["1.5rule", columnName]
    descriptive.loc["Greater", columnName]=dataset[columnName].quantile(0.75)+descriptive.loc["1.5rule", columnName]
    descriptive.loc["Min", columnName]=dataset[columnName].min()
    descriptive.loc["Max", columnName]=dataset[columnName].max()
    descriptive.loc["LowOutLier", columnName]=dataset[columnName].min()<descriptive.loc["Lesser", columnName]
    descriptive.loc["HighOutLier", columnName]=dataset[columnName].max()>descriptive.loc["Greater", columnName]

descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
LowOutLier,False,False,False,False,False,False,False
HighOutLier,False,False,False,False,False,False,False